# These are supported funding model platforms

github: ["https://github.com/guruh46"]
patreon: # Replace with a single Patreon username
open_collective: ["https://opencollective.com/guruh46"]
ko_fi: ["https://ko-fi.com/guruh46"]
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ["https://liberapay.com/Guruh46/"]
issuehunt: ["https://issuehunt.io/profiles/6a6961ce-ff29-4112-bd85-c77c24b8dde0"]
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: ["https://polar.sh/dashboard/httpsgithubcomguruh46"]
buy_me_a_coffee: ["https://buymeacoffee.com/irawanguru4"]
thanks_dev: ["https://thanks.dev/e/gh/guruh46/dependencies"]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
